"""Add resume storage and match analysis

Revision ID: 0a0a618e4399
Revises: 06c0ad10dbf7
Create Date: 2026-05-17 00:20:04.197622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0a618e4399'
down_revision: Union[str, Sequence[str], None] = '06c0ad10dbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_match_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('match_result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_index(op.f('ix_resume_match_analysis_id'), 'resume_match_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_resume_match_analysis_user_id'), 'resume_match_analysis', ['user_id'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Saved'::character varying"))
    op.add_column('users', sa.Column('resume', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume')
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Saved'::character varying"))
    op.drop_index(op.f('ix_resume_match_analysis_user_id'), table_name='resume_match_analysis')
    op.drop_index(op.f('ix_resume_match_analysis_id'), table_name='resume_match_analysis')
    op.drop_table('resume_match_analysis')
    # ### end Alembic commands ###
