"""add cascade delete to job_analysis

Revision ID: 0bc518755d0e
Revises: 179c993406ee
Create Date: 2026-05-13 19:41:37.817041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc518755d0e'
down_revision: Union[str, Sequence[str], None] = '179c993406ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_analysis', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('job_analysis_job_id_fkey'), 'job_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'job_analysis', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('job_analysis_job_id_fkey'), 'job_analysis', 'jobs', ['job_id'], ['id'])
    op.alter_column('job_analysis', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
