"""add job_id to job_analysis

Revision ID: 5702a146549b
Revises: 8169cffc03b1
Create Date: 2026-05-12 11:54:35.017068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5702a146549b'
down_revision: Union[str, Sequence[str], None] = '8169cffc03b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analysis', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_analysis', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_analysis', type_='foreignkey')
    op.drop_column('job_analysis', 'job_id')
    # ### end Alembic commands ###
