"""Add job_analysis table

Revision ID: 8169cffc03b1
Revises: eaf90b6be364
Create Date: 2026-05-08 23:22:07.871395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8169cffc03b1'
down_revision: Union[str, Sequence[str], None] = 'eaf90b6be364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analysis_id'), 'job_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_analysis_id'), table_name='job_analysis')
    op.drop_table('job_analysis')
    # ### end Alembic commands ###
