"""Added resume text

Revision ID: e672b9344975
Revises: 0a0a618e4399
Create Date: 2026-05-17 20:05:00.072324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e672b9344975'
down_revision: Union[str, Sequence[str], None] = '0a0a618e4399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_text', sa.Text(), nullable=True))
    op.drop_column('users', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'resume_text')
    # ### end Alembic commands ###
